//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Review_ID { get; set; }
        public string Review_Name { get; set; }
        public string Review_Email { get; set; }
        public string Review_Detail { get; set; }
        public Nullable<System.DateTime> Review_Datetime { get; set; }
        public int Review_Product { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
