//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShopper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOrderDetail
    {
        public int Product_ID { get; set; }
        public int Order_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Product_Name { get; set; }
        public Nullable<double> Product_Price { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
    }
}
